clientes/urls.py
from django.urls import path
# from .views import persons_list
# from .views import persons_new
# from .views import persons_update
# from .views import persons_delete
from .views import PersonList
from .views import PersonDetail
from .views import PersonCreate
from .views import PersonUpdate
from .views import PersonDelete
from .views import ProdutoBulk

urlpatterns = [
    # path('list/', persons_list, name="person_list"),
    # path('new/', persons_new, name="person_new"),
    # path('update/<int:id>/', persons_update, name="persons_update"),
    # path('delete/<int:id>/', persons_delete, name="persons_delete"),
    path('person_list/', PersonList.as_view(), name="person_list_cbv"),
    path('person_detail/<int:pk>/', PersonDetail.as_view(), name="person_detail_cbv"),
    path('person_delete/<int:pk>/', PersonDelete.as_view(), name="person_delete_cbv"),
    path('person_update/<int:pk>/', PersonUpdate.as_view(), name="person_update_cbv"),
    path('person_create/', PersonCreate.as_view(), name="person_create_cbv"),
    path('produto_bulk/', ProdutoBulk.as_view(), name="produto_bulk"),
]

gestao_clientes/urls.py
from django.contrib import admin
from django.urls import path, include
from clientes import urls as clientes_urls
from vendas import urls as vendas_urls
from home import urls as home_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include(home_urls)),
    path('clientes/', include(clientes_urls)),
    path('vendas/', include(vendas_urls)),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#
#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),
#
#     ] + urlpatterns

admin.site.site_header = 'Gestão de Clientes'                    # default: "Django Administration"
admin.site.index_title = 'Administração'                 # default: "Site administration"
admin.site.site_title = 'Seja Bem Vindo'

home/urls.py
from django.urls import path
from .views import home, my_logout, HomePageView, MyView, politica_de_privacidade
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', home, name="home"),
    path('politica-de-privacidade', politica_de_privacidade, name="politica_de_privacidade"),
    path('logout/', my_logout, name="logout"),
    path('home2/', TemplateView.as_view(template_name='home2.html'), name="home2"),
    path('home3/', HomePageView.as_view(template_name='home3.html'), name="home3"),
    path('view/', MyView.as_view()),
]

vendas/urls.py
from django.urls import path
from .views import (
             dash, novo_pedido, novoItemPedido, delete_ItemPedido,
             listavendas, edit_Pedido, delete_Pedido, edit_ItemPedido )

app_name = "vendas"
urlpatterns = [
    path('', listavendas, name="listavendas"),
    path('novo-pedido/', novo_pedido, name="novo_pedido"),
    path('novo-item-pedido/<int:venda>/', novoItemPedido, name="novo_item_pedido"),
    path('edit-pedido/<int:venda>/', edit_Pedido, name="edit_pedido"),
    path('delete-item-pedido/<int:item>/', delete_ItemPedido, name="delete_item_pedido"),
    path('edit-item-pedido/<int:item>/', edit_ItemPedido, name="edit_item_pedido"),
    path('delete-pedido/<int:venda>/', delete_Pedido, name="delete_pedido"),
    path('dashboard/', dash, name="dash"),
]

clientes/models.py
from django.db import models
from django.core.mail import send_mail, mail_admins, send_mass_mail
from django.template.loader import render_to_string

class Documento(models.Model):
    num_doc = models.CharField(max_length=50)

    def __str__(self):
        return self.num_doc


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField()
    salary = models.DecimalField(max_digits=6, decimal_places=2)
    bio = models.TextField()
    photo = models.ImageField(upload_to='clients_photos', null=True, blank=True)
    doc = models.OneToOneField(Documento, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('deletar_clientes', 'Deletar Clientes'),
        )

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    @property
    def nome_completo(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        super(Person, self).save(*args, **kwargs)

        data = {'cliente': self.first_name}
        plain_text = render_to_string('clientes/emails/novo_cliente.txt', data)
        html_email = render_to_string('clientes/emails/novo_cliente.html', data)

        send_mail(
            'Novo cliente cadastrado',
            plain_text,
            'ocrsha@gmail.com',
            ['ocrsha@gmail.com'],
            html_message=html_email,
            fail_silently=False,
        )

        mail_admins(
            'Novo cliente cadastrado',
            plain_text,
            html_message=html_email,
            fail_silently=False,
        )

        message1 = ('Subject here', 'Here is the message', 'from@example.com', ['first@example.com', 'other@example.com'])
        message2 = ('Another Subject', 'Here is another message', 'from@example.com', ['second@test.com'])
        send_mass_mail((message1, message2), fail_silently=False)

clientes/forms.py
from django.forms import ModelForm
from .models import Person


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'age', 'salary', 'bio', 'photo']

clientes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Person
from produtos.models import Produto
from vendas.models import Venda
from .forms import PersonForm
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse


class PersonList(LoginRequiredMixin, ListView):
    model = Person

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        primeiro_acesso = self.request.session.get('primeiro_acesso', False)

        if not primeiro_acesso:
            context['message'] = 'Seja bem vindo ao seu primeiro acesso Hoje'
            self.request.session['primeiro_acesso'] = True
        else:
            context['message'] = 'Você já acessou hoje'

        return context


class PersonDetail(LoginRequiredMixin, DetailView):
    model = Person

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        return Person.objects.select_related('doc').get(id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['vendas'] = Venda.objects.filter(pessoa_id=self.object.id)
        return context


class PersonCreate(LoginRequiredMixin, CreateView):
    model = Person
    fields = ['first_name', 'last_name', 'age', 'salary', 'bio', 'photo']
    success_url = "/clientes/person_list"


class PersonUpdate(LoginRequiredMixin, UpdateView):
    model = Person
    fields = ['first_name', 'last_name', 'age', 'salary', 'bio', 'photo']
    # success_url = reverse_lazy('person_list_cbv')
    # funcao que substitui o success_url
    def get_success_url(self):
        return reverse_lazy('person_list_cbv')


class PersonDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = ('clientes.deletar_clientes',)
    model = Person
    #success_url = reverse_lazy('person_list_cbv')

    def get_success_url(self):
        return reverse_lazy('person_list_cbv')

class ProdutoBulk(View):
    def get(self, request):
        from random import randint

        produtos = ['leite', 'sabonete', 'macarrao', 'azeite', 'trigo', 'oleo', 'arroz', 'carne']
        lista_produtos = []

        for produto in produtos:
            x = randint(3, 11)
            a = Produto(descricao=produto, preco=x)
            lista_produtos.append(a)

        Produto.objects.bulk_create(lista_produtos)

        return HttpResponse("bulk_create")


# @login_required
# def persons_list(request):
#     persons = Person.objects.all()
#     qtd = Person.objects.all().count()
#
#     context = {
#             'persons': persons,
#             'qtd': qtd,
#      }
#
#     return render(request, 'clientes/person.html', context )
#
#
# @login_required
# def persons_new(request):
#     if not request.user.has_perm('clientes.add_person'):
#         return HttpResponse('<h2>Nao Autorizado</h2>')
#     # elif not request.user.is_superuser:
#     #     return HttpResponse('<h2>Nao é super Usuario</h2>')
#     form = PersonForm(request.POST or None, request.FILES or None)
#     footer_message = "Novo Cliente - Django WEB"
#     if form.is_valid():
#         form.save()
#         return redirect('person_list')
#     return render(request, 'clientes/person_form.html', {'form': form, 'footer_message': footer_message })
#
#
# @login_required
# def persons_update(request, id):
#     person = get_object_or_404(Person, pk=id)
#     form = PersonForm(request.POST or None, request.FILES or None, instance=person)
#
#     if form.is_valid():
#         form.save()
#         return redirect('person_list')
#
#     return render(request, 'clientes/person_form.html', {'form': form})


# @login_required
# def persons_delete(request, id):
#     person = get_object_or_404(Person, pk=id)
#
#     if request.method == 'POST':
#         person.delete()
#         return redirect('person_list')
#
#     return render(request, 'clientes/person_delete_confirm.html', {'person': person})



















    # a função abaixo substitui a variavel success_url

    def get_success_url(self):
        return reverse_lazy('person_list_cbv')

clientes/templates/clientes/footer.html
{% load my_tags %} {% load my_filters %}

<footer class="footer">
    <div class="container">
        <span class="text-muted foot_message ">{% footer_message %}</span>

        <div id="hora_server">

            {% current_time " %I:%M %p" as the_time %} {{ the_time }}

        </div>
    </div>
</footer>

clientes/templates/clientes/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>

    <h1 class="hello">Ola mundo</h1>
    <b>Meu nome e fulano</b> <br>

    <img src="{% static 'django.jpg' %}" alt="">

</body>
</html>

clientes/templates/clientes/person.html
<h3>Listagem de Pessoas</h3>

<h4>Informe aqui o nome do novo usuario</h4>

<a href="{% url 'person_create_cbv' %}">Novo Usuario</a><br><br> {% for person in object_list %}

<a href="{% url 'person_detail_cbv' person.id %}">{{ person }}</a><br><br> {% endfor %}

clientes/templates/clientes/person_confirm_delete.html
{% extends 'base.html' %} {% block title %} Confirmacao {% endblock %} {% block main %}

<h1>Tem certeza que deseja deletar {{ person.first_name }} </h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock %} {% block footer %} {% include 'clientes/footer.html' %} {% endblock %}

clientes/templates/clientes/person_delete_confirm.html
{% extends 'base.html' %} {% block title %} Confirmacao {% endblock %} {% block main %}

<h1>Tem certeza que deseja deletar {{ person.first_name }} </h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

{% endblock %} {% block footer %} {% include 'clientes/footer.html' %} {% endblock %}

clientes/templates/clientes/person_detail.html
Nome: {{ object.first_name }}<br>
Sobrenome: {{ object.last_name }}<br>
Documento: {{ object.doc }}<br>

<h2>vendas</h2>
<p>{% for venda in vendas %}</p>
  <p>Venda id: {{ venda.id }}</p>
  <h3>Lista de Pordutos</h3>
  <ul>
    {% for produto in venda.produtos.all %}
      <li>{{ produto.id }} - {{ produto.descricao }}</li>
    {% endfor %}
  </ul>
{% endfor %}

<p>{{ now|date }}</p>

<a href="{% url 'person_update_cbv' object.pk %}">Alterar</a>
<a href="{% url 'person_delete_cbv' object.pk %}">Deletar</a>

clientes/templates/clientes/person_form.html
{% extends 'base.html' %} {% load bootstrap %} {% block title %} Administracao {% endblock %} {% block main %}
<h3>Novo cliente - {{ request.session.message }}</h3>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% filter force_escape|upper %} This text will be HTML-escaped, and will appear in all lowercase. {% endfilter %} {% endblock %} {% block footer %} {% include 'clientes/footer.html' %} {% endblock %}

clientes/templates/clientes/person_list.html
{% extends 'base.html' %} {% load my_tags %} {% block title %} Administracao {% endblock %} {% block main %}

<div class="row">
    <div class="col">
        {% footer_message %}
        <h5>{{ qtd }}</h5>
    </div>

    <div class="col-6">
        <h3>Listagem de clientes </h3>
        <ul class="list-group">
            <p>{{ message }}</p>
            {% for person in object_list %}
            <li class="list-group-item">
                <a href="{% url 'person_update_cbv' person.pk %}">{{ person.nome_completo|title }}</a>
                <a href="{% url 'person_delete_cbv' person.pk %}" class="trash-item">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
            </li>
            {% empty %}
            <h4>Desculpe, essa pessoa não consta na lista!!!</h4>
            {% endfor %}
        </ul>

        <br>

        <a href="{% url 'person_create_cbv' %}" class="btn btn-primary"> Novo cliente</a>
        <a href="{% url 'vendas:dash' %}" class="btn btn-primary"> Vendas</a><br>
        {% now "SHORT_DATETIME_FORMAT" %}
    </div>

    <div class="col">
        {% if user.is_authenticated %}
        <p>{{ request.session.message }}
            <a href="{% url 'logout' %}">
                <span class="badge badge-dark">Sair</span>
            </a>
        </p>

        {% endif %}
    </div>
</div>


{% endblock %} {% block footer %} {% include 'clientes/footer.html' %} {% endblock %}

clientes/templates/clientes/person_update_form.html
<h3>Alterar Cliente</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Alterar">
    </form>