gestao_clientes/urls.py
from django.contrib import admin
from django.urls import path, include
from clientes import urls as clientes_urls
from vendas import urls as vendas_urls
from home import urls as home_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include(home_urls)),
    path('clientes/', include(clientes_urls)),
    path('vendas/', include(vendas_urls)),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#
#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),
#
#     ] + urlpatterns

admin.site.site_header = 'Gestão de Clientes'                    # default: "Django Administration"
admin.site.index_title = 'Administração'                 # default: "Site administration"
admin.site.site_title = 'Seja Bem Vindo'

home/urls.py
from django.urls import path
from .views import home, my_logout, HomePageView, MyView, politica_de_privacidade
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', home, name="home"),
    path('politica-de-privacidade', politica_de_privacidade, name="politica_de_privacidade"),
    path('logout/', my_logout, name="logout"),
    path('home2/', TemplateView.as_view(template_name='home2.html'), name="home2"),
    path('home3/', HomePageView.as_view(template_name='home3.html'), name="home3"),
    path('view/', MyView.as_view()),
]

vendas/urls.py
from django.urls import path
from .views import (
             dash, novo_pedido, novoItemPedido, delete_ItemPedido,
             listavendas, edit_Pedido, delete_Pedido, edit_ItemPedido )

app_name = "vendas"
urlpatterns = [
    path('', listavendas, name="listavendas"),
    path('novo-pedido/', novo_pedido, name="novo_pedido"),
    path('novo-item-pedido/<int:venda>/', novoItemPedido, name="novo_item_pedido"),
    path('edit-pedido/<int:venda>/', edit_Pedido, name="edit_pedido"),
    path('delete-item-pedido/<int:item>/', delete_ItemPedido, name="delete_item_pedido"),
    path('edit-item-pedido/<int:item>/', edit_ItemPedido, name="edit_item_pedido"),
    path('delete-pedido/<int:venda>/', delete_Pedido, name="delete_pedido"),
    path('dashboard/', dash, name="dash"),
]

vendas/models.py
from django.db import models
from django.db.models import Sum, F, FloatField
from django.db.models.signals import post_save
from django.dispatch import receiver
from clientes.models import Person
from produtos.models import Produto
from .managers import VendaManager

class Venda(models.Model):
    numero = models.DecimalField(max_digits=4, decimal_places=0)
    valor = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    desconto = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    impostos = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    pessoa = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    nfe_emitida = models.BooleanField(default=False)

    objects = VendaManager()

    class Meta:
        permissions = (
            ('setar_nfe', 'Usuario pode alterar parametro'),
            ('ver_dashboard', 'Pode ver o dashboard'),
            ('perm3', 'Permissao 3'),

        )

    def get_raw_vendas(self):
        return Venda.objects.raw('select * from vendas_venda where id = %s', ['7',])    

    def calcular_total(self):
        tot = self.itempedido_set.all().aggregate(
            tot_ped=Sum((F('qtd') * F('produto__preco')) - F('desconto'), output_field=FloatField())
        )['tot_ped'] or 0

        tot = tot - float(self.impostos) - float(self.desconto)
        #self.valor = tot
        Venda.objects.filter(id=self.id).update(valor=tot)
    # def get_total(self):
    #     tot = 0
    #     for produto in self.produtos.all():
    #         tot += produto.preco
    #     return (tot - self.desconto) - self.impostos

    def __str__(self):
        return self.numero

class ItemPedido(models.Model):
    venda = models.ForeignKey(Venda, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    qtd = models.FloatField()
    desconto = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return '{}  -  {}'.format(self.venda.numero, self.produto.descricao)


@receiver(post_save, sender=ItemPedido)
def update_vendas_total(sender, instance, **kwargs):
    instance.venda.calcular_total()
    #instance.save()

@receiver(post_save, sender=Venda)
def update_vendas_total2(sender, instance, **kwargs):
    instance.calcular_total()
    #instance.save()
    #Venda.objects.filter(id=instance.id).update(total=total)

vendas/forms.py
from django import forms
from .models import ItemPedido

class ItemPedidoForm(forms.Form):
    produto_id = forms.CharField(label='ID do Produto', max_length=100)
    qtd = forms.IntegerField(label='Quantidade')
    desconto = forms.DecimalField(label='Desconto', max_digits=4, decimal_places=2)


class ItemDoPedidoModelForm(forms.ModelForm):
    class Meta:
        model = ItemPedido
        fields = ['qtd', 'desconto',]

vendas/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from .models import Venda
from .models import ItemPedido
from .forms import ItemPedidoForm, ItemDoPedidoModelForm
from django.utils.formats import sanitize_separators

class DashboardView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('vendas.ver_dashboard'):
            return HttpResponse('Acesso Negado, voce precisa de permissao')

        return super(DashboardView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        data = {}
        data['media'] = Venda.objects.media()
        data['media_desc'] = Venda.objects.media_desc()
        data['soma'] = Venda.objects.soma()
        data['min'] = Venda.objects.min()
        data['max'] = Venda.objects.max()
        data['n_count'] = Venda.objects.n_count()
        data['n_count_nfe'] = Venda.objects.n_count_nfe()


        return render(request, 'vendas/dashboard.html', data)

class NovoPedido(View):
    def get(self, request):
        return render(request, 'vendas/novo-pedido.html')

    def post(self, request):
        data = {}
        data['form_item'] = ItemPedidoForm()
        data['numero'] = int(request.POST['numero'])
        data['desconto'] = sanitize_separators(request.POST['desconto'])
        data['venda_id'] = request.POST['venda_id']

        if data['venda_id']:
            venda = Venda.objects.get(id=data['venda_id'])
            venda.desconto = data['desconto']
            venda.numero = data['numero']
            venda.save()
        else:
            venda = Venda.objects.create(numero=data['numero'], desconto=data['desconto'])

        itens = venda.itempedido_set.all()
        data['venda'] = venda
        data['itens'] = itens
        return render( request, 'vendas/novo-pedido.html', data)



class NovoItemPedido(View):
    def get(self, request, pk):
        pass

    def post(self, request, venda):
        data = {}
        item = ItemPedido.objects.filter(produto_id=request.POST['produto_id'], venda_id=venda)
        if item:
            data['mensagem'] = 'Item já incluido na lista de venda'
            item = item[0]
        else:
            item = ItemPedido.objects.create(
                produto_id=request.POST['produto_id'],
                qtd=request.POST['qtd'],
                desconto=request.POST['desconto'], venda_id=venda
            )
            
        data['item'] = item
        data['form_item'] = ItemPedidoForm()
        data['numero'] = item.venda.numero
        data['desconto'] = item.venda.desconto
        data['venda'] = item.venda
        data['itens'] = item.venda.itempedido_set.all()

        return render(request, 'vendas/novo-pedido.html', data)


class ListaVendas(View):
    def get(self, request):
        vendas = Venda.objects.all()
        return render(request, 'vendas/listavendas.html', {'vendas': vendas })


class EditPedido(View):
    def get(self, request, venda):
        data = {}
        venda = Venda.objects.get(id=venda)
        data['form_item'] = ItemPedidoForm()
        data['numero'] = venda.numero
        data['desconto'] = float(venda.desconto)
        data['venda'] = venda
        data['itens'] = venda.itempedido_set.all()
        return render(request, 'vendas/novo-pedido.html', data)


class DeletePedido(View):
    def get(self, request, venda):
        venda = Venda.objects.get(id=venda)
        return render(request, 'vendas/delete-pedido-confirm.html', {'venda': venda})

    def post(self, request, venda):
        venda = Venda.objects.get(id=venda)
        venda.delete()
        return redirect('vendas:listavendas')


class DeleteItemPedido(View):
    def get(self, request, item):
        item_pedido = ItemPedido.objects.get(id=item)
        return render(
            request, 'vendas/delete-itempedido-confirm.html', {'item_pedido': item_pedido })

    def post(self, request, item):
        item_pedido = ItemPedido.objects.get(id=item)
        venda_id = item_pedido.venda.id
        item_pedido.delete()
        request.method = 'GET'
        return redirect('vendas:edit_pedido', venda=venda_id)


class EditItemPedido(View):
    def get(self, request, item):
        item_pedido = ItemPedido.objects.get(id=item)
        form = ItemDoPedidoModelForm(instance=item_pedido)
        return render(
            request, 'vendas/edit-itempedido.html', {'item_pedido': item_pedido, 'form': form })

    def post(self, request, item):
        item_pedido = ItemPedido.objects.get(id=item)
        item_pedido.qtd = request.POST['qtd']
        item_pedido.desconto = request.POST['desconto']

        item_pedido.save()
        venda_id = item_pedido.venda.id
        return redirect('vendas:edit_pedido', venda=venda_id)


dash = DashboardView.as_view()
novo_pedido = NovoPedido.as_view()
novoItemPedido = NovoItemPedido.as_view()
listavendas = ListaVendas.as_view()
edit_Pedido = EditPedido.as_view()
delete_Pedido = DeletePedido.as_view()
delete_ItemPedido = DeleteItemPedido.as_view()
edit_ItemPedido = EditItemPedido.as_view()


























'''
'''

vendas/templates/vendas/dashboard.html
{% extends 'base.html' %}

{% block main %}
<h2>Dash Board</h2>
  <ul>
    <li>Valor médio: R$ {{ media|floatformat:2 }}</li>
    <li>Desconto médio: R$ {{ media_desc|floatformat:2 }}</li>
    <li>Valor Minimo: R$ {{ min|floatformat:2  }}</li>
    <li>Valor Maximo: R$ {{ max|floatformat:2  }}</li>
    <li>Valor Total: R$ {{ soma|floatformat:2  }}</li>
    <li>Nº Pedidos: {{ n_count }}</li>
    <li>Notas Emitidas: {{ n_count_nfe }}</li>
  </ul>
{% endblock main %}

vendas/templates/vendas/delete-itempedido-confirm.html
{% extends 'base.html' %}

{% block main %}
  <h3>Tem certeza que quer deletar o pedido? {{ item_pedido }}</h3>
    <form action="{% url 'vendas:delete_item_pedido' item_pedido.id %}"method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-main">Confirmar</button>
    </form>
{% endblock main %}

vendas/templates/vendas/delete-pedido-confirm.html
{% extends 'base.html' %}

{% block main %}
  <h3>Tem certeza que quer deletar o pedido? {{ venda.id }}</h3>
    <form action="{% url 'vendas:delete_pedido' venda.id %}"method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-main">Confirmar</button>
    </form>
{% endblock main %}

vendas/templates/vendas/edit-itempedido.html
{% extends 'base.html' %}

{% block main %}
  <h3>Editando item : {{ item_pedido }}</h3>
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="text">Atualizar</button>
  </form>
{% endblock main %}

vendas/templates/vendas/listavendas.html
{% extends 'base.html' %}

{% block main %}
  <h2>Listagem de Vendas</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Numero</th>
        <th scope="col">Desconto</th>
        <th scope="col">Valor</th>
      </tr>
    </thead>
    <tbody>
      {% for venda in vendas %}
        <tr>
          <td>{{ venda.id }}</td>
          <td>{{ venda.numero }}</td>
          <td>{{ venda.desconto }}</td>
          <td>{{ venda.valor }}</td>
          <td>
            <a href="{% url 'vendas:edit_pedido' venda.id %}">
              Editar
            </a>
          </td>
          <td>
            <a href="{% url 'vendas:delete_pedido' venda.id %}">
              Excluir
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'vendas:novo_pedido' %}"> Nova Venda</a>
  {% endblock main %}

vendas/templates/vendas/novo-pedido.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
<div class="row">
  <div class="col-4">
  <h4>Novo Pedido</h4>
  <form method="POST" action="{% url 'vendas:novo_pedido' %}">
    {% csrf_token %}
    <h5>Pedido numero: {{ venda.numero }}</h5>
    <input type="text" name="numero" class="form-control" value="{{numero}}"
            placeholder="Numero" required=True>

    <label for="desconto">Desconto</label><br>
    <input type="text" name="desconto" id="desconto" value="{{desconto}}"
            placeholder="Desconto" class="form-control" required=True>

    <input type="hidden" value="{{venda.id}}" name="venda_id">
    <br>
    <button type="submit" class="btn btn-main">Enviar</button><br>
  </form>
    <b>Total: R$ {{ venda.valor }}</b> <br>
    <b>Desc: R$ {{ venda.desconto }}</b>
  </div>
</div>
{% endblock main %}

{% block extra %}

{% if venda %}

{% if mensagem %}
  {{ mensagem }}
{% endif %}
<div class="row">
  <div class="col-4">
  <form action="{% url 'vendas:novo_item_pedido' venda.id %}" method="POST">
    {% csrf_token %}
    {{ form_item|bootstrap }}
  <button class="btn btn-info">Incluir</button>
</form>
</div>
</div>

<div class="row">
  <div class="col-8">
  <h2>Listagem de itens</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Descrição</th>
        <th scope="col">Qtd</th>
        <th scope="col">Desc</th>
        <th scope="col">Editar</th>
        <th scope="col">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for item in itens %}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.produto.descricao }}</td>
          <td>{{ item.qtd }}</td>
          <td>{{ item.desconto }}</td>
          <td scope="col">
            <a href="{% url 'vendas:edit_item_pedido' item.id %}"><i class="fa fa-pencil"></i></a>
          </td>
          <td scope="col">
            <a href="{% url 'vendas:delete_item_pedido' item.id %}"><i class="fa fa-trash"></i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
    </div>
  {% endif %}
{% endblock extra %}